name: celestya
description: "Dating app MVP with auth, profile and compatibility quiz."
publish_to: 'none'
version: 1.0.3+20

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  appinio_swiper: ^2.1.1
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.1.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  speech_to_text: ^7.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  uuid: ^4.4.0
  workmanager: ^0.9.0+3
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.3
  record: ^6.1.2
  audioplayers: ^6.5.1
  path: ^1.9.1
  url_launcher: ^6.3.1
  intl: ^0.19.0
  app_links: ^6.0.0
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/orange_texture.png
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: false # para Play Store (Android). Cámbialo a true cuando vayas a compilar iOS.
  image_path: "assets/icons/icon_1024.png"

  # Android Adaptive Icon (se ve mejor en teléfonos modernos)
  # adaptive_icon_foreground: "assets/icons/adaptive_fg.png"
  # adaptive_icon_background: "assets/icons/adaptive_bg.png"
  min_sdk_android: 23
