name: Celestya
description: "Dating app MVP with auth, profile and compatibility quiz."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  appinio_swiper: ^2.1.1
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.1.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/orange_texture.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon_1024.png"

  # Android Adaptive Icon (se ve mejor en telÃ©fonos modernos)
  adaptive_icon_foreground: "assets/icons/adaptive_fg.png"
  adaptive_icon_background: "assets/icons/adaptive_bg.png"
  min_sdk_android: 21

